# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

        
definitions: 
  services: 
    postgres: 
      image: postgres 
      environment: 
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        DATABASE_URL: postgres://postgres@127.0.0.1:5432/testdb      

pipelines:
  default:
    - step:
        name: Database
        script:
          - echo "Hola"
        
    - step:
        name: Build and restore Project
        image: microsoft/dotnet:2.0-sdk
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          - export PROJECT_NAME=real_lumino_encuestas
          - export TEST_NAME=real_lumino_encuestas.Test
          - dotnet restore ReAl.Lumino.Encuestas/ReAl.Lumino.Encuestas.csproj
          - dotnet build ReAl.Lumino.Encuestas/ReAl.Lumino.Encuestas.csproj
          - dotnet test ReAl.Lumino.Encuestas.Test
          - dotnet publish ReAl.Lumino.Encuestas/ReAl.Lumino.Encuestas.csproj
        artifacts:
          - ReAl.Lumino.Encuestas/bin/Debug/netcoreapp2.0/publish/**
        services:
          - postgres

     
