# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

definitions: 
  services: 
    postgres: 
      image: postgres 
      environment: 
        POSTGRES_DB: db_encuestas
        POSTGRES_USER: postgres

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        image: microsoft/dotnet:2.0-sdk
        script: # Modify the commands below to build your repository.
          - psql -c 'drop database if exists db_encuestas;' -U postgres
          - psql -c 'create database db_encuestas;' -U postgres
          - export PROJECT_NAME=real_lumino_encuestas
          - export TEST_NAME=real_lumino_encuestas.Test
          - dotnet restore ReAl.Lumino.Encuestas/ReAl.Lumino.Encuestas.csproj
          - dotnet build ReAl.Lumino.Encuestas/ReAl.Lumino.Encuestas.csproj
          - dotnet test ReAl.Lumino.Encuestas.Test
          - dotnet publish ReAl.Lumino.Encuestas/ReAl.Lumino.Encuestas.csproj
        services:
          - postgres

     
